spring:
  application:
    name: ecommerce
  datasource:
    url: jdbc:h2:mem:ecommerce
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

logging:
  level:
    org:
      springframework:
        security: DEBUG

jwt:
  secret: 4380E00D947E0E4552715993
  tokenValidityMilliseconds: 1800000


