spring:
  application:
    name: ecommerce
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

logging:
  level:
    org:
      springframework:
        security: DEBUG

jwt:
  secret: 4380E00D947E0E4552715993
  tokenValidityMilliseconds: 1800000


